[package]
name = "xremap"
version = "0.3.3"
edition = "2021"
description = "Dynamic key remapp for X and Wayland"
license = "MIT"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.53"
clap = { version = "3.0.14", features = ["derive"] }
clap_complete = "3.0.6"
derive-where = "1.0.0-rc.2"
env_logger = "0.9.0"
evdev = "0.11.3"
indoc = "1.0"
lazy_static = "1.4.0"
log = "0.4.14"
nix = "0.23.1"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
serde_with = { version = "1.11", features = ["chrono"] }
serde_yaml = "0.8"
swayipc = { version = "2.7.2", optional = true }
x11_rs = { package = "x11", version = "2.19.1", features = ["xlib"], optional = true }
zbus = { version = "2.1.1", optional = true }

[features]
gnome = ["zbus"]
sway = ["swayipc"]
x11 = ["x11_rs"]
